mainapp/urls.py
from django.urls import path
from .views import BaseView, ProductDetailView, CategoryDetailView, CartView

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart')
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),   # Запуск проекта в браузере
]

if settings.DEBUG:
    '''
    # Если сервер находиться в режиме DEBUG используем локальный медиа контент который записывается в корень проекта 
    и не находиться на сервере
    '''
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


'''
import re_path
        #     urlpatterns += re_path(r'^static/(?P<path>.*)$')
'''

mainapp/models.py
from PIL import Image   # for work with images
import sys   # module of size images

from django.db import models
from django.contrib.auth import get_user_model  # v.1 Используем юзера, который указан в настройках
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from io import BytesIO   # for work with images
from django.core.files.uploadedfile import InMemoryUploadedFile   # for resize download images
from django.urls import reverse   # make url for object product
from django.utils.translation import gettext_lazy


User = get_user_model()  # v.1.1 Используем юзера, который указан в скрытых настройках (settings.AUTH_USER_MODEL)


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewename):
    ct_model = obj.__class__._meta.model.name
    return reverse(viewename, kwargs={'ct_model': ct_model, 'slug': obj.slug})


"""
Представление которое будет отвечать за стартовую страницу будет имитировать 1 запрос и доставать весь список
товаров которое мы хотим отобразить на главной странице class LatestProductsManager
ContentType Микрофрейм ворк который видет модели которые есть в INSTALLED_APPS в settings предоставляя 
универсальный интерфейс
"""


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class LatestProductsManager:  # 1:13:00 Просмотреть суть этого класса с моделями.

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')  # Отображение определенных товаров первыми в списке
        products = []  # Финальный список товаров
        ct_models = ContentType.objects.filter(model__in=args)  # Запрос ContentType фильтруя модели которые находятся в аргументах args
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(
                        products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True
                    )
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):  # In site pages for side bar see the product category and Quantity

    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
        'Смартфоны': 'smartphone__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):

    # parents_category = models.ForeignKey('self', blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(
        unique=True)
    objects = CategoryManager()
    ''' 
    короткое название-метка, содержит только буквы числа нижнее подчеркивание дефис. 
    Используются в URL(Category/nootebook)
    '''
    prepopulated_fields = {"slug": (
    "title",)}  # позволяет определить поля, которые получают значение основываясь на значениях других полей

    class Meta:
        verbose_name = gettext_lazy('category')
        verbose_name_plural = gettext_lazy('categories')

    def __str__(self):  # отображение категории в админке
        return self.name   # f'{self.name} | parent - {self.parents_category}' if self.parent else self.name  # Показывает вложенные категории в админке

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    MIN_RESOLUTIONS = (400, 400)
    MAX_RESOLUTIONS = (900, 900)
    MAX_IMAGE_SIZE = 3145728  # ~ 3mb

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория',
                                 on_delete=models.CASCADE)
    '''
    Обект Category класса Product наследуеться(связан) от класса Category / 
    при удалении обекта удаляеться все связи с ним (данные)  
                                 '''
    title = models.CharField(max_length=255, verbose_name='Название продукта')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание товара', null=True)  # Поле может быть пустым null=True
    price = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        verbose_name='Цена'
    )  # Параметры цены, максимальное колличество символов до запятой(9) и после(2)

    def __str__(self):
        return self.title


'''
    def save(self, *args, **kwargs):
        # 1. Example for save images upper then 400px and lower then 900px
        image = self.image
        img = Image.open(image)
        min_height, min_width = self.MIN_RESOLUTIONS
        max_height, max_width = self.MAX_RESOLUTIONS
        if img.height < min_height or img.width < min_width:
            raise MinResolutionErrorException('Разрешение изображения меньше минимального')
        if img.height > max_height or img.width > max_width:
            raise MaxResolutionErrorException('Разрешение изображения больше максимального')

        # 2. Example cut the images to 200px x 200px
        image = self.image
        img = Image.open(image)
        new_img = img.convert('RGB')
        resized_new_img = new_img.resize((200, 200), Image.ANTIALIAS)
        filestream = BytesIO()
        resized_new_img.save(filestream, 'JPEG', quality=90)
        filestream.seek(0)
        name = '{}.{}'.format(*self.image.name.split('.'))
        self.image = InMemoryUploadedFile(
            filestream, 'ImageField', name, 'jpeg/image', sys.getsizeof(filestream), None
        )
        super().save(*args, **kwargs)
'''


class Notebook(Product):
    name = models.CharField(max_length=255, verbose_name='Имя')
    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплея')
    processor_freq = models.CharField(max_length=255, verbose_name='Частота процессора')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    video = models.CharField(max_length=255, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Время работы аккамулятора')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)   # {Категория} : {Какой товар}

    def get_absolute_url(self):   # for url view
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    name = models.CharField(max_length=255, verbose_name='Имя')
    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display_type = models.CharField(max_length=255, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=255, verbose_name='Разрешение екрана')
    accum_volume = models.CharField(max_length=255, verbose_name='Обьем батареи')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name='Наличие sd карты')
    sd_volume_max = models.CharField(
        max_length=255, null=True, blank=True, verbose_name='Максимальный обем встроенной памяти'
    )
    main_camp_mp = models.CharField(max_length=255, verbose_name='Главная камера')
    frontal_camp_mp = models.CharField(max_length=255, verbose_name='Фронтальная камера')

    def __str__(self):
        return "{} : {}".format(self.category.name, self.title)

    def get_absolute_url(self):   # for url view
        return get_product_url(self, 'product_detail')

    # @property  # This all for check box sd
    # def sd(self):
    #     if self.sd:
    #         return 'Да'
    #     return 'Нет'


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE
    )
    '''
    Микрофрейм ворк который видет модели которые есть в INSTALLED_APPS в settings предоставляя универсальный интерфейс
    '''
    object_id = models.PositiveIntegerField()  # Индификатор инстанс этой модели
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    '''
    Колличество выбранного товара в корзине, по умолчанию 1, Подобно IntegerField, но должно быть либо положительным, 
    либо нулевым (0). Значения от 0 до 2147483647 безопасны во всех базах данных, поддерживаемых Django.
    '''
    final_price = models.DecimalField(max_digits=9, decimal_places=2,
                                      verbose_name='Цена')  # Финальная цена всех товаров в корзине

    def __str__(self):
        return "Продукт: {} (для корзины)".format(
            self.content_object.title)


class Cart(models.Model):
    owner = models.ForeignKey('Customer', verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(
        CartProduct,
        blank=True,
        related_name='related_cart'
    )  # Связь многие ко многим к CartProduct
    total_products = models.PositiveIntegerField(default=0)  # Корректное колличество товаров в корзине шт.

mainapp/views.py
from django.shortcuts import render
from django.views.generic import DetailView, View
from .models import Notebook, Smartphone, Category, LatestProducts, Customer, Cart
from .mixins import CategoryDetailMixin


class BaseView(View):  # In site pages for side bar see the product category and Quantity

    def get(self, request, *args, **kwargs):
        categories = Category.objects.get_categories_for_left_sidebar()
        products = LatestProducts.objects.get_products_for_main_page(
            'notebook', 'smartphone', with_respect_to='notebook'
        )
        context = {
            'categories': categories,
            'products': products,
        }
        return render(request, 'base.html', context)


# class ProductDetailView(CategoryDetailMixin, DetailView):   # for url views for all models:
#     # 127.0.0.1:8000/products/notebook/notebookHP/
#     # 127.0.0.1:8000/products/smartphone/smartphone/
#
#     CT_MODEL_MODEL_CLASS = {
#         'notebook': Notebook,
#         'smartphone': Smartphone
#     }
#
#     def dispatch(self, request, *args, **kwargs):
#         self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
#         self.queryset = self.model._base_manager.all()
#         return super().dispatch(request, *args, **kwargs)
#
#     context_object_name = 'product'
#     template_name = 'product_detail.html'
#     slug_url_kwarg = 'slug'


class ProductDetailView(CategoryDetailMixin, DetailView):

    CT_MODEL_MODEL_CLASS = {
        'notebook': Notebook,
        'smartphone': Smartphone
    }

    def dispatch(self, request, *args, **kwargs):
        self.model = self.CT_MODEL_MODEL_CLASS[kwargs['ct_model']]
        self.queryset = self.model._base_manager.all()
        return super().dispatch(request, *args, **kwargs)

    context_object_name = 'product'
    template_name = 'product_detail.html'
    slug_url_kwarg = 'slug'


class CategoryDetailView(CategoryDetailMixin, DetailView):  # for sidebar left menu views

    model = Category
    queryset = Category.objects.all()
    context_object_name = 'category'
    template_name = 'category_detail.html'
    slug_url_kwarg = 'slug'  # То что будет искаться в url pass, в пути урла.


class CartView(View):

    def get(self, request, *args, **kwargs):
        customer = Customer.objects.get(user=request.user)
        cart = Cart.objects.get(owner=customer)
        categories = Category.objects.get_categories_for_left_sidebar()
        context = {
            'cart': cart,
            'categories': categories
        }
        return render(request, 'cart.html', context)

mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{# !!! if check box "Наличие sd карты" in admin panel on you can type text if not - can't type text !!! #}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
    {#console.log('Hello')  {# admin pages in smartphone product in inspect console print Hello for example#}
(function($) {
        $('#id_sd').on('click', function(){
            {#console.log('Click')#}{# admin pages in smartphone product in inspect console print Click for example#}
            if($('#id_sd').prop('checked') == true){
                $('#id_sd_volume_max').prop('readonly', false)
                $('#id_sd_volume_max').val('')
                $('#id_sd_volume_max').css('background', 'white')
            }else {
                $('#id_sd_volume_max').prop('readonly', true)
                $('#id_sd_volume_max').val('')
                $('#id_sd_volume_max').css('background', 'lightgray')
            }
        })
})(django.jQuery);
</script>
{% endblock %}

mainapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Shop Homepage - Start Bootstrap Template</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Custom styles for this template -->
  <link href="css/shop-homepage.css" rel="stylesheet">

</head>
<style>
    body {
      padding-top: 56px;
    }
</style>
<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base' %}">Django 3 | E-commerce</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3 mt-5">  <!-- In site pages for side bar see the product category and Quantity -->
        <div class="list-group">
          {% for category in categories %}
          <a href="{{ category.url }}" class="list-group-item">{{ category.name }} ({{ category.count }})</a>
          {% endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">
        {% block content %}
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success alert-dismissible fade show mt-3" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
        {% endif %}
        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="{% static '/first_slider.jpg' %}" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="{% static '/second_slider.jpg' %}" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="{% static '/third_slider.jpg' %}" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
{#{{ product.get_absolute_url }}#}
        <div class="row">
          {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href=""><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} грн.</h5>
{#                <a href="{% url 'add_to_cart' ct_model=product.get_model_name slug=product.slug %}">#}
{#                  <button class="btn btn-danger">Добавить в корзину</button>#}
                </a>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <!-- /.row -->
      {% endblock content %}
      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/cart.html
{% extends 'base.html' %}


{% block content %}

    {{ cart }}

{% endblock content %}

mainapp/templates/category_detail.html
{% extends 'base.html' %}


{% block content %}

    {{ category.name }}

{% endblock content %}

mainapp/templates/notebook_specifications.html
    <table class="table">
      <tbody>
      <tr>
          <td>Диагональ</td>
          <td>{{ product.diagonal }}</td>
      </tr>
      <tr>
          <td>Дисплей</td>
          <td>{{ product.display_type }}</td>
      </tr>
      <tr>
          <td>Процессор</td>
          <td>{{ product.processor_freq }}</td>
      </tr>
      <tr>
          <td>Оперативная память</td>
          <td>{{ product.ram }}</td>
      </tr>
      <tr>
          <td>Видео Карта</td>
          <td>{{ product.video }}</td>
      </tr>
      <tr>
          <td>Время работы от аккумулятора</td>
          <td>{{ product.time_without_charge }}</td>
      </tr>
      </tbody>
</table>

mainapp/templates/product_detail.html
{%  extends 'base.html' %}
{% load specifications %}
{% block content %}
    <nav aria-label="breadcrumb" class="mt-3">{# bootstrap indent mt-3 #}
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
        <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.title }} </li>
      </ol>
    </nav>
    <div class="row">{# div will be in one line 'row'#}
        <div class="col-md-4">
            <img src="{{ product.image.url }}" class="img-fluid" alt="image">
        </div>
        <div class="col-md-8">
            <h3>{{ product.title }}</h3>
            <p> Цена: {{ product.price }} грн.</p>
            <p> Описание: {{ product.description }}</p>
        </div>
            <p class="mt-4"> Характеристики: </p>

            {# first filter using notebook_specifications.html and smartphone_specifications.html #}
{#            {% if product.category.slug == 'notebooks' %}{# chack if category notebooks or another #}
{#                {% include 'notebook_specifications.html' %}{# include templates notebook_specifications.html #}
{#            {% else %}#}
{#                {% include 'smartphone_specifications.html' %}{# include templates smartphone_specifications.html #}
{#            {% endif %}#}

            {{ product|product_spec }}
            {# for example add another filter number2, create templatetags and specifications.py#}
    </div>
{% endblock content %}

mainapp/templates/smartphone_specifications.html
    <table class="table" id=widths>
      <tbody>
      <tr>
          <td>Диагональ</td>
          <td>{{ product.diagonal }}</td>
      </tr>
      <tr>
          <td>Тип дисплея</td>
          <td>{{ product.display_type }}</td>
      </tr>
      <tr>
          <td>Разрешение екрана</td>
          <td>{{ product.resolution }}</td>
      </tr>
      <tr>
          <td>Обем батареи</td>
          <td>{{ product.accum_volume }}</td>
      </tr>
      <tr>
          <td>Оперативная память</td>
          <td>{{ product.ram }}</td>
      </tr>
      <tr>
          <td>Поддержка CD карты</td>
          <td>{{ product.sd }}</td>
      </tr>
      <tr>
          <td>Максимальный обем встроеной памяти</td>
          <td>{{ product.sd_volume_max }}</td>
      </tr>
      <tr>
          <td>Главная камера</td>
          <td>{{ product.main_camp_mp }}</td>
      </tr>
      <tr>
          <td>Фронтальная камера</td>
          <td>{{ product.frontal_camp_mp }}</td>
      </tr>
      </tbody>
</table>